version: '3'
services:
  dock-clock:
    build:
      context: .
      dockerfile: Dockerfile-dev
    container_name: dock-clock
    networks:
      - dock-clock
    ports:
      - '3000:3000'
    environment:
     - HOST=0.0.0.0
    command: npm run start
networks:
  dock-clock:
    driver: bridge
